// AUTO-GENERATED by scripts/build-geo.mjs. Do not edit by hand.
// Source geometry: Natural Earth via the world-atlas package (public domain).

export const JOURNEY_VIEWBOX = { width: 1000, height: 560 } as const;
/** Land, France and India outlines, cropped to the map window, as a static image. */
export const JOURNEY_BASE_SRC = "/images/geo/journey-base.svg";
export const JOURNEY_WINDOW = { x: 150, y: 150, w: 700, h: 400 } as const;
export const JOURNEY_ARC_PATH = "M705,480L664.6,446.7L621.1,414.1L573.6,383L521.4,354.4L493.3,341.6L464,330L433.4,319.8L401.7,311.4L369,305L335.6,300.7L301.8,298.6L267.9,299";
export const JOURNEY_POINTS = { hyderabad: [705,480], montpellier: [267.9,299] } as const;
