// AUTO-GENERATED by scripts/build-geo.mjs. Do not edit by hand.
// Source geometry: Natural Earth via the world-atlas package (public domain).

export const MINI_WORLD_VIEWBOX = { width: 320, height: 160 } as const;
export const MINI_WORLD_SRC = "/images/geo/mini-world.svg";
export const MINI_WORLD_PORTS = {"shanghai":[263,60],"singapore":[252,91],"busan":[268,56],"nhavaSheva":[224,72],"jebelAli":[207,66],"rotterdam":[163,39],"hamburg":[168,37],"leHavre":[160,41],"fos":[164,47],"newYork":[99,50],"losAngeles":[61,57],"santos":[120,117],"durban":[186,123],"sydney":[287,127]} as const;
