// AUTO-GENERATED by scripts/build-geo.mjs. Do not edit by hand.
// Source geometry: Natural Earth via the world-atlas package (public domain).

export const WORLD_VIEWBOX = { width: 1000, height: 470 } as const;
/** Land outline lives in /public/images/geo/world-land.svg (loaded lazily as an image). */
export const WORLD_LAND_SRC = "/images/geo/world-land.svg";
export const WORLD_PORTS = {"shanghai":[821.8,171.3],"singapore":[788.5,267.8],"busan":[837.3,158.8],"nhavaSheva":[699.2,211],"jebelAli":[648.4,191.4],"rotterdam":[510.8,105.4],"hamburg":[523.8,100.4],"leHavre":[500.2,112.9],"fos":[512.4,132.1],"newYork":[310.8,140.8],"losAngeles":[189.4,163.2],"santos":[374.8,349.2],"durban":[582.5,368.3],"sydney":[897,381.2]} as const;
export type PortId = keyof typeof WORLD_PORTS;
